import React from 'react'
import PropTypes from 'prop-types'
import { NextPage } from 'next'
import Head from 'next/head'
import Navbar from '../components/Navbar'

const Login: NextPage = () => {
    return (
        <>
        <Head>
          <title>Rate a Joke | Login</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <Navbar/>
        <h1>Login</h1>
        </>
  
    )
  }
  
export default Login
